openapi: 3.1.0

info:
  title: Film Directors
  version: 1.0.0

servers:
  - url: https://film-directors.onrender.com/api/v1
    description: Production server
  - url: localhost:9000/api/v1
    description: Development server

tags:
  - name: Directors
  - name: Countries

paths:
  /directors:
    get:
      tags:
        - Directors
      summary: Returns an array of directors.
      responses:
        '200':
          description: A JSON array of director names.
        '400':
          description: Validation error.
    post:
      tags:
        - Directors
      summary: Create a new director.
      requestBody:
        description: Create a director.
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DirectorsPost'
        required: true
      responses:
        '201':
          description: Successful process.
        '400':
          description: Missing  data / Validation error.
  /directors/{directorId}:
    parameters:
      - in: path
        name: directorId
        schema:
          type: string
        required: true
    get:
      tags:
        - Directors
      summary: Returns a director by Id.
      operationId: getDirectorId
      responses:
        '200':
          description: OK
        '400':
          description: Validation error.
        '404':
          description: 'Id: {id} does not exists'
    put:
      tags:
        - Directors
      summary: Update a director with required data.
      operationId: putDirectorId
      requestBody:
        description: Update a director with required data.
        content:
          aplication/json:
            schema:
              $ref: '#/components/schemas/DirectorsPut'
        required: true
      responses:
        '200':
          description: 'Director with Id: {id} edited succesfully.'
        '400':
          description: Missing  data / Validation error.
        '404':
          description: Invalid Id.
    patch:
      tags:
        - Directors
      summary: Update a director by Id.
      operationId: patchDirectorId
      requestBody:
        description: Update a director.
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DirectorsPatch'
        required: true
      responses:
        '200':
          description: 'Director with Id: {id} edited succesfully.'
        '400':
          description: Validation error.
        '404':
          description: Invalid Id.
    delete:
      tags:
        - Directors
      summary: Delete a director.
      operationId: deleteDirectorId
      responses:
        '404':
          description: Invalid Id.
  /countries:
    get:
      tags:
        - Countries
      summary: Returns an array of countries.
      responses:
        '200':
          description: A JSON array of country names.
        '400':
          description: Validation error.
    post:
      tags:
        - Countries
      summary: Create a new country.
      requestBody:
        description: Create a country.
        content:
          aplication/json:
            schema:
              $ref: '#/components/schemas/Countries'
        required: true
      responses:
        '201':
          description: Successful process.
        '400':
          description: Invalid data / Validation error.
  /countries/{countryId}:
    parameters:
      - in: path
        name: countryId
        schema:
          type: string
        required: true
    get:
      tags:
        - Countries
      summary: Returns a country by Id.
      operationId: getCountryId
      responses:
        '200':
          description: OK.
        '400':
          description: Validation error.
        '404':
          description: 'Id: ${id} does not exists'
    patch:
      tags:
        - Countries
      summary: Update a country by Id.
      operationId: patchCountryId
      requestBody:
        description: Update a country.
        content:
          aplication/json:
            schema:
              $ref: '#/components/schemas/Countries'
        required: true
      responses:
        '200':
          description: 'Country with Id: {id} edited succesfully.'
        '400':
          description: Validation error.
        '404':
          description: Invalid Id.
    delete:
      tags:
        - Countries
      summary: Delete a country by Id.
      operationId: deleteCountryId
      responses:
        '404':
          description: Invalid Id

components:
  schemas:
    DirectorsPost:
      required:
        - name
        - lastName
        - countryId
        - firsFilm
        - lastFilm
      type: object
      properties:
        photograph:
          type: string
          format: binary
          contentMediaType:
            - image/png
            - image/jpg
            - image/jpeg
          contentEncoding: base64
          examples:
            - photograph.png
        name:
          type: string
          examples:
            - Irvin
        lastName:
          type: string
          examples:
            - Welsh
        age:
          type: integer
          examples:
            - 34
        countryId:
          type: integer
        alive:
          type: boolean
          examples:
            - true
        birthday:
          type: string
          format: date
          examples:
            - '1975-12-28T00:00:00.000Z'
        films:
          type: integer
          examples:
            - 4
        firsFilm:
          type: string
          examples:
            - First Film
        lastFilm:
          type: string
          examples:
            - Last Film
    DirectorsPut:
      required:
        - name
        - lastName
        - countryId
        - birthday
        - films
        - firsFilm
        - lastFilm
      type: object
      properties:
        photograph:
          type: string
          format: binary
          contentMediaType:
            - image/png
            - image/jpg
            - image/jpeg
          contentEncoding: base64
          examples:
            - photograph.png
        name:
          type: string
          examples:
            - Irvin
        lastName:
          type: string
          examples:
            - Welsh
        age:
          type: integer
          examples:
            - 34
        countryId:
          type: integer
        alive:
          type: boolean
          examples:
            - true
        birthday:
          type: string
          format: date
          examples:
            - '1975-12-28T00:00:00.000Z'
        films:
          type: integer
          examples:
            - 4
        firsFilm:
          type: string
          examples:
            - First Film
        lastFilm:
          type: string
          examples:
            - Last Film
    DirectorsPatch:
      type: object
      properties:
        photograph:
          type: string
          format: binary
          contentMediaType:
            - image/png
            - image/jpg
            - image/jpeg
          contentEncoding: base64
          examples:
            - photograph.png
        name:
          type: string
          examples:
            - Irvin
        lastName:
          type: string
          examples:
            - Welsh
        age:
          type: integer
          examples:
            - 34
        countryId:
          type: integer
        alive:
          type: boolean
          examples:
            - true
        birthday:
          type: string
          format: date
          examples:
            - '1975-12-28T00:00:00.000Z'
        films:
          type: integer
          examples:
            - 4
        firsFilm:
          type: string
          examples:
            - First Film
        lastFilm:
          type: string
          examples:
            - Last Film
    Countries:
      required:
        - name
      type: object
      properties:
        name:
          type: string
          examples:
            - Norway